### ISSUE TITLE
Uncaught exception: uninitialized constant Mongoid while installation

### ISSUE THREAD

**Issue by exocode** [assembler/attachinary#56]
When I try to install attachinary on Ruby 1.9.3 and rails-3.2.13

I got this error:

```
Uncaught exception: uninitialized constant Mongoid
/Users/jan/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/attachinary-1.2.6/lib/attachinary/orm/mongoid/file.rb:3:in `<class:File>'
/Users/jan/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/attachinary-1.2.6/lib/attachinary/orm/mongoid/file.rb:2:in `<module:Attachinary>'
/Users/jan/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/attachinary-1.2.6/lib/attachinary/orm/mongoid/file.rb:1:in `<top (required)>'
/Users/jan/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/attachinary-1.2.6/lib/attachinary/orm/mongoid.rb:4:in `require_relative'
/Users/jan/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/attachinary-1.2.6/lib/attachinary/orm/mongoid.rb:4:in `<top (required)>'
/Users/jan/RubymineProjects/untitled/config/application.rb:6:in `require'
/Users/jan/RubymineProjects/untitled/config/application.rb:6:in `<top (required)>'
/Users/jan/.gem/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:53:in `require'
/Users/jan/.gem/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:53:in `block in <top (required)>'
/Users/jan/.gem/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:50:in `tap'
/Users/jan/.gem/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:50:in `<top (required)>'
/Users/jan/RubymineProjects/untitled/script/rails:6:in `require'
/Users/jan/RubymineProjects/untitled/script/rails:6:in `<top (required)>'
```

Can you provide a solution for this please?

PS: Love your gem (it's really one ) :-)

**Comment by murdoch** [comment]
@mediatainment thanks for helping me fix this! I had the same problem with ActiveRecord. If I find time I will create a pull request with an updated README as this is likely to affect others. Thanks again.
